"use client";

import type { SalesSummaryReport } from "@/lib/types";
import { SalesSummaryReportTable } from "@/components/sales/sales-summary-report-table";

const SYSTEM_NAME = "GENSAN POS & INVENTORY";
const SYSTEM_FOOTER = "GENSAN POS & INVENTORY SYSTEM";

type SalesSummaryReportPrintProps = {
  report: SalesSummaryReport;
  storeName?: string;
  storeAddress?: string;
  printedBy?: string;
  /** Pre-rendered QR data URL (required for reliable browser print). */
  qrDataUrl?: string | null;
};

function formatPeriodLabel(report: SalesSummaryReport): string {
  if (report.from === report.to) {
    return new Date(report.from).toLocaleDateString("en-PH", {
      timeZone: "Asia/Manila",
      month: "long",
      day: "numeric",
      year: "numeric",
    });
  }
  return report.periodLabel;
}

function formatPrintedDateTime(iso: string): string {
  return new Date(iso).toLocaleString("en-PH", {
    timeZone: "Asia/Manila",
    month: "long",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });
}

export function SalesSummaryReportPrint({
  report,
  storeName = "GensanPOS",
  storeAddress,
  printedBy = "Owner",
  qrDataUrl = null,
}: SalesSummaryReportPrintProps) {
  const periodLabel = formatPeriodLabel(report);
  const printStamp = report.printedAtLabel;
  const printedDateTime = formatPrintedDateTime(report.generatedAt);
  const printedByName = report.printedBy?.trim() || printedBy;

  return (
    <div id="sales-summary-print" className="sales-summary-print-root">
      <div className="sales-summary-print-stamp sales-summary-print-locked" aria-hidden>
        {printStamp}
      </div>
      <div className="sales-summary-print-body text-black">
        <header className="sales-summary-print-header text-center">
          {qrDataUrl ? (
            <div className="sales-summary-print-qr">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={qrDataUrl}
                alt="Verification QR"
                width={120}
                height={120}
                className="sales-summary-print-qr-img mx-auto"
                decoding="sync"
                loading="eager"
              />
              <p className="mt-0.5 text-[6px] leading-tight text-black/70">
                Scan to verify
              </p>
            </div>
          ) : null}
          <h1 className="sales-summary-print-title">DAILY SALES REPORT</h1>
          <p className="sales-summary-print-brand">{SYSTEM_NAME}</p>
          <p className="sales-summary-print-store">{storeName}</p>
          {storeAddress ? (
            <p className="sales-summary-print-address uppercase">{storeAddress}</p>
          ) : null}
          <p className="sales-summary-print-meta">
            <span className="font-medium">Period:</span> {periodLabel}
          </p>
          <p
            className="sales-summary-print-meta sales-summary-print-locked"
            data-server-stamp="true"
          >
            <span className="font-medium">Printed:</span> {printStamp}
          </p>
          {report.verificationReportCode ? (
            <p className="sales-summary-print-meta sales-summary-print-locked">
              <span className="font-medium">Report ID:</span> {report.verificationReportCode}
            </p>
          ) : null}
        </header>

        <SalesSummaryReportTable
          report={report}
          compact
          forPrint
          className="sales-summary-table mt-1"
        />

        <footer className="sales-summary-print-footer">
          <div className="sales-summary-print-signatures">
            <div>
              <p className="font-bold">Prepared By:</p>
              <p className="sig-line">{report.preparedFor ?? ""}</p>
            </div>
            <div>
              <p className="font-bold">Approved By:</p>
              <p className="sig-line" />
            </div>
          </div>
          <div className="sales-summary-print-info">
            <p>
              <span className="font-semibold">Printed By:</span> {printedByName}
            </p>
            <p className="sales-summary-print-locked" data-server-stamp="true">
              <span className="font-semibold">Printed Date:</span> {printedDateTime}
            </p>
            <p className="col-span-2">
              <span className="font-semibold">Generated by:</span>
              <br />
              {SYSTEM_FOOTER}
            </p>
          </div>
        </footer>
      </div>
    </div>
  );
}
