"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ShieldCheck, AlertCircle, Loader2 } from "lucide-react";
import { getPublic } from "@/lib/api";
import { formatCurrency } from "@/lib/format";
import type { SalesReportVerificationView } from "@/lib/types";

export default function VerifyReportPage() {
  const params = useParams<{ code: string }>();
  const code = params.code;
  const [data, setData] = useState<SalesReportVerificationView | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!code) return;
    const normalized = decodeURIComponent(code).trim();
    getPublic<SalesReportVerificationView>(
      `/api/reports/verify/${encodeURIComponent(normalized)}`
    )
      .then(setData)
      .catch((e: Error) => setError(e.message || "Verification not found"))
      .finally(() => setLoading(false));
  }, [code]);

  return (
    <div className="flex min-h-full items-center justify-center bg-muted/40 p-4">
      <div className="w-full max-w-md rounded-xl border bg-card p-6 shadow-lg">
        {loading ? (
          <div className="flex items-center justify-center gap-2 py-10 text-muted-foreground">
            <Loader2 className="h-5 w-5 animate-spin" />
            Verifying report…
          </div>
        ) : error ? (
          <div className="flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">
            <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
            <p>{error}</p>
          </div>
        ) : data ? (
          <>
            <div className="mb-6 text-center">
              <ShieldCheck className="mx-auto mb-2 h-8 w-8 text-primary" aria-hidden />
              <p className="text-sm font-semibold uppercase tracking-wide">{data.systemName}</p>
              <h1 className="mt-1 text-xl font-bold">{data.reportTitle}</h1>
            </div>

            <dl className="space-y-4 text-sm">
              <VerifyRow label="Report ID" value={data.reportId} mono />
              <VerifyRow label="Generated" value={data.generatedAtLabel || data.printedAtLabel} />
              {data.generatedBy ? (
                <VerifyRow label="Generated By" value={data.generatedBy} />
              ) : null}
              <VerifyRow label="Period" value={data.periodLabel || data.reportDateRange} />
              <VerifyRow label="Total Sales" value={formatCurrency(data.totalSales)} highlight />
              <VerifyRow label="Status" value={data.status} status />
            </dl>

            <details className="mt-6 rounded-lg border bg-muted/20 p-3 text-xs text-muted-foreground">
              <summary className="cursor-pointer font-medium text-foreground">
                Full verification details
              </summary>
              <dl className="mt-3 space-y-2">
                <VerifyRow label="Report date range" value={data.reportDateRange} compact />
                <VerifyRow label="Net sales" value={formatCurrency(data.netSales)} compact />
                <VerifyRow label="Table net total" value={formatCurrency(data.totalLineAmount)} compact />
                <VerifyRow label="Gross sales" value={formatCurrency(data.grossSales)} compact />
              </dl>
            </details>

            {data.storeName ? (
              <p className="mt-6 text-center text-xs text-muted-foreground">{data.storeName}</p>
            ) : null}
          </>
        ) : null}
      </div>
    </div>
  );
}

function VerifyRow({
  label,
  value,
  mono,
  highlight,
  status,
  compact,
}: {
  label: string;
  value: string;
  mono?: boolean;
  highlight?: boolean;
  status?: boolean;
  compact?: boolean;
}) {
  return (
    <div className={`flex flex-col gap-0.5 ${compact ? "" : "sm:flex-row sm:items-baseline sm:justify-between"}`}>
      <dt className="text-muted-foreground">{label}:</dt>
      <dd
        className={`font-medium tabular-nums ${mono ? "font-mono text-xs" : ""} ${
          highlight ? "text-lg text-primary" : ""
        } ${status ? "text-emerald-600" : ""}`}
      >
        {value}
      </dd>
    </div>
  );
}
